<a href="https://colab.research.google.com/github/baiju012/Machine-Learning/blob/main/ann_practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

**Read the data**


In [ ]:
dataset=pd.read_csv("Churn_Modelling.csv")

In [ ]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225       NaN  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850     Spain  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225       NaN  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

**Handle null values**

In [ ]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [ ]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             1
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
dataset.describe()

RowNumber    CustomerId  CreditScore          Age        Tenure  \
count  10000.00000  1.000000e+04  10000.00000  9999.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.48290    38.924392      5.012800   
std     2886.89568  7.193619e+04     96.72014    10.487263      2.892174   
min        1.00000  1.556570e+07    225.00000    18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.00000    32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.00000    37.000000      5.000000   
75%     7500.25000  1.575323e+07    717.25000    44.000000      7.000000   
max    10000.00000  1.581569e+07    850.00000    92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76489.148004       1.530200      0.70550        0.515100   
std     62399.589585       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127651.035000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [ ]:
dataset["Age"].mean()

38.924392439243924

In [ ]:
dataset["Age"].fillna(dataset["Age"].mean(),inplace=True)
dataset["Geography"].fillna(dataset["Geography"].mode()[0],inplace=True)
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace=True)


In [ ]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
mode most frequent value
france=10
germany=10
spain=5


SyntaxError: ignored

In [ ]:
dataset["Geography"].mode()[0]

'France'

encoding

1.nominal encoding----one hot encoding
2.ordinal encoding---label encoding

education     salary
btech        3
mtech      2
phd             1   



state        Germany     france    spain
germany       1            0         0
france        0            1         0
spain         0            0          1
3-1=2

5 inputs
1 column with 3 categories

2
5+2=7




In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Geography"]=le.fit_transform(dataset["Geography"])
dataset["Gender"]=le.fit_transform(dataset["Gender"])

In [ ]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender        Age  \
0          1    15634602  Hargrave          619          0       0  42.000000   
1          2    15647311      Hill          225          0       0  41.000000   
2          3    15619304      Onio          629          0       0  42.000000   
3          4    15701354      Boni          699          0       0  39.000000   
4          5    15737888  Mitchell          850          2       0  43.000000   
5          6    15574012       Chu          645          2       1  44.000000   
6          7    15592531  Bartlett          619          0       1  50.000000   
7          8    15656148    Obinna          376          1       1  38.924392   
8          9    15792365        He          501          0       1  44.000000   
9         10    15592389        H?          684          0       1  43.000000   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

**splittng dependent and independent variables**

In [ ]:
#daset.iloc[rows,column]
x=dataset.iloc[:,3:13]
y=dataset.iloc[:,13:14]

In [ ]:
x.head()

CreditScore  Geography  Gender   Age  Tenure    Balance  NumOfProducts  \
0          619          0       0  42.0       2       0.00              1   
1          225          0       0  41.0       1   83807.86              1   
2          629          0       0  42.0       8  159660.80              3   
3          699          0       0  39.0       1       0.00              2   
4          850          2       0  43.0       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [ ]:
y.head()

Exited
0       1
1       0
2       1
3       0
4       0

In [ ]:
x.shape

(10000, 10)

In [ ]:
y.shape

(10000, 1)

In [ ]:
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13:14].values

In [ ]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

**onehot encoding**



In [ ]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()

In [ ]:
z=one.fit_transform(x[:,1:2]).toarray()

In [ ]:
z

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
x=np.delete(x,1,axis=1)

In [ ]:
x=np.concatenate((z,x),axis=1)

In [ ]:
x.shape

(10000, 12)

**train test split**

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [ ]:
x_train.shape

(7000, 12)

In [ ]:
y_train.shape

(7000, 1)

In [ ]:
x_test.shape

(3000, 12)

In [ ]:
a=[1,2,3,4,5,6,7]
b=[1,0,1,5,5,3,2]

In [ ]:
for i in range(5):
  a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.3,random_state=0)
  print("with random state",a_train)

with random state [4, 1, 6, 5]
with random state [4, 1, 6, 5]
with random state [4, 1, 6, 5]
with random state [4, 1, 6, 5]
with random state [4, 1, 6, 5]


In [ ]:
for i in range(5):
  a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.3)
  print("withoutrandom state",a_train)

withoutrandom state [4, 3, 7, 1]
withoutrandom state [4, 2, 6, 3]
withoutrandom state [2, 1, 7, 5]
withoutrandom state [3, 1, 7, 6]
withoutrandom state [7, 6, 5, 2]


feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_train=sc.fit_transform(x_train)

In [ ]:
x_train

array([[ 0.98468863, -0.56987189, -0.57295135, ...,  0.64198477,
         0.96683535, -0.76862426],
       [ 0.98468863, -0.56987189, -0.57295135, ...,  0.64198477,
        -1.03430227, -1.39359887],
       [ 0.98468863, -0.56987189, -0.57295135, ..., -1.55766936,
         0.96683535, -1.49739308],
       ...,
       [ 0.98468863, -0.56987189, -0.57295135, ...,  0.64198477,
        -1.03430227,  1.41400417],
       [-1.01554945, -0.56987189,  1.7453489 , ...,  0.64198477,
         0.96683535,  0.84625811],
       [-1.01554945,  1.75478035, -0.57295135, ...,  0.64198477,
        -1.03430227,  0.32689267]])

In [ ]:
ANN starts
Model building
	1.import all the necessary libraries
	2. add input layer (inputs==n=no.o input features,weights,activation function=Relu)
	3.add hidden layer(inputs=2n   n/2,weights,activation function=Relu)
	4.add op layer(no.of output,weights,activation function)
	Regression	(1,weights,activation function=Relu)
	Binary       	(1,weights,activation function=Sigmoid)
	Categorical	(no.of categories,weights,activation function=softmax)

	5.compile the model(loss function,acuuracy,optimizer)
	Regression	(MSE,MSE,minibatch/adam/adadelta/rmsprop)
	Binary       	(binary cross entropy,accuracy score,minibatch/adam/adadelta/rmsprop)
	Categorical	(no.of categories,weights,minibatch/adam/adadelta/rmsprop)

	6.fit the model (x_train,y_train,epochs,batch_size)


In [ ]:
#	1.import all the necessary libraries
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model=Sequential()

In [ ]:
#	2. add input layer (inputs==n=no.o input features,weights,activation function=Relu)
model.add(Dense(units=12,activation="relu",kernel_initializer="random_uniform"))

In [ ]:
#	3.add hidden layer(inputs=2n   n/2,weights,activation function=Relu)
model.add(Dense(units=6,activation="relu",kernel_initializer="random_uniform"))


In [ ]:
#	3.add hidden layer(inputs=2n   n/2,weights,activation function=Relu)
model.add(Dense(units=6,activation="relu",kernel_initializer="random_uniform"))

In [ ]:
#4.add op layer(no.of output,weights,activation function)
model.add(Dense(units=1,activation="sigmoid",kernel_initializer="random_uniform"))

In [ ]:
#5.compile the model(loss function,acuuracy,optimizer)
model.compile(optimizer="adam",loss="binary_crossentropy",metrics="accuracy")

In [ ]:
#	6.fit the model (x_train,y_train,epochs,batch_size)
model.fit(x_train,y_train,epochs=10,batch_size=32)

#7000/32=219

Epoch 1/10
219/219 [==============================] - 2s 2ms/step - loss: 0.5807 - accuracy: 0.7957
Epoch 2/10
219/219 [==============================] - 0s 2ms/step - loss: 0.4380 - accuracy: 0.7977
Epoch 3/10
219/219 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.7977
Epoch 4/10
219/219 [==============================] - 0s 1ms/step - loss: 0.4274 - accuracy: 0.7977
Epoch 5/10
219/219 [==============================] - 0s 1ms/step - loss: 0.4239 - accuracy: 0.7977
Epoch 6/10
219/219 [==============================] - 0s 1ms/step - loss: 0.4211 - accuracy: 0.7977
Epoch 7/10
219/219 [==============================] - 0s 1ms/step - loss: 0.4189 - accuracy: 0.7977
Epoch 8/10
219/219 [==============================] - 0s 1ms/step - loss: 0.4170 - accuracy: 0.8101
Epoch 9/10
219/219 [==============================] - 0s 1ms/step - loss: 0.4160 - accuracy: 0.8239
Epoch 10/10
219/219 [==============================] - 0s 1ms/step - loss: 0.4144 - accuracy: 0.8274

In [ ]:
ypred=model.predict(x_test)

94/94 [==============================] - 0s 1ms/step


In [ ]:
ypred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
y_test

array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [ ]:
>0.5    1
<0.5    0

In [ ]:
ypred=ypred>0.5

In [ ]:
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,ypred)

0.7926666666666666