<a href="https://colab.research.google.com/github/baiju012/Machine-Learning/blob/main/Classification_(for_demo).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# provides powerful and versatile array computations, mathematical functions
import numpy as np

# offers various data structures and operations for manipulating numerical data and time series.
import pandas as pd


In [ ]:
df = pd.read_csv('/content/Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
# checking shape
df.shape

(400, 5)

In [ ]:
# checking info of all  here one are object so it has to convert into int by encoding

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [ ]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [ ]:
# no use of user id so we will drop it
# for building a model we don't need unique value

df.drop(['User ID'],axis=1,inplace=True)

In [ ]:
df

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [ ]:

df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

# Encoding --- 3 types ---
"""
1. One hot encoding
2. Label encoding
3. manual encoding
"""


In [ ]:
# Manual encoding  for Gender you may use other

df['Gender'] = df['Gender'].replace({'Male':0,'Female':1})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    int64
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(4)
memory usage: 12.6 KB


In [ ]:
# need all row and 0-2 column
x = df.iloc[:,0:3]
x

Gender  Age  EstimatedSalary
0         0   19            19000
1         0   35            20000
2         1   26            43000
3         1   27            57000
4         0   19            76000
..      ...  ...              ...
395       1   46            41000
396       0   51            23000
397       1   50            20000
398       0   36            33000
399       1   49            36000

[400 rows x 3 columns]

In [ ]:
# only need purchaded column

y = df.iloc[:,3:]
y

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [ ]:
# split training and testing

from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=10)

In [ ]:
#  handle both numerical and categorical features, and supports various regularization methods to prevent overfitting
from sklearn.linear_model import LogisticRegression

#  handle both numerical and categorical features, and supports various criteria to measure the quality of a split
from sklearn.tree import DecisionTreeClassifier

# allows controlling the number of trees and the size of the sub-samples
from sklearn.ensemble import RandomForestClassifier

In [ ]:
lr = LogisticRegression()

In [ ]:
dt = DecisionTreeClassifier()

In [ ]:
rf = RandomForestClassifier()

In [ ]:
lr.fit(xtrain,ytrain)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
dt.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [ ]:
rf.fit(xtrain,ytrain)

<ipython-input-23-b2cd86e6079b>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(xtrain,ytrain)


RandomForestClassifier()

In [ ]:
ypred_lr = lr.predict(xtest)
ypred_dt = dt.predict(xtest)
ypred_rf = rf.predict(xtest)

In [ ]:
ypred_lr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ypred_dt

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
ypred_rf

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
# # now for understanding of classification report
from sklearn.metrics import confusion_matrix

In [ ]:

confusion_matrix(ytest,ypred_lr)

array([[52,  0],
       [28,  0]])

In [ ]:
confusion_matrix(ytest,ypred_dt)

array([[45,  7],
       [ 1, 27]])

In [ ]:
 # see diagonal  say that random forest is working fine and better so we will go through this model
confusion_matrix(ytest,ypred_rf)

array([[47,  5],
       [ 1, 27]])

In [ ]:
# Save the model

import pickle

In [ ]:
pickle.dump(rf,open('classification_rf.pkl','wb'))