In [1]:
import numpy as np
import pandas as pd


In [2]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='EZb4PLP-Cipb8VDQRAcNDgCkGFbHm_bp1_9LsXCBlGSE',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us-south.cloud-object-storage.appdomain.cloud')

bucket = 'ibmhc-donotdelete-pr-egmygsyvmylpln'
object_key = 'Social_Network_Ads.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
'''df = pd.read_csv('/content/Social_Network_Ads.csv')
df.head()'''

In [3]:
df.shape

(400, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [7]:
df.drop(['User ID'],axis=1,inplace=True)

In [8]:
df

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [9]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [10]:
df['Gender'] = df['Gender'].replace({'Male':0,'Female':1})

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    int64
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(4)
memory usage: 12.6 KB


In [12]:
x = df.iloc[:,0:3]
x

Gender  Age  EstimatedSalary
0         0   19            19000
1         0   35            20000
2         1   26            43000
3         1   27            57000
4         0   19            76000
..      ...  ...              ...
395       1   46            41000
396       0   51            23000
397       1   50            20000
398       0   36            33000
399       1   49            36000

[400 rows x 3 columns]

In [13]:
y = df.iloc[:,3:]
y

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=10)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [17]:
lr = LogisticRegression()

In [18]:
dt = DecisionTreeClassifier()

In [19]:
rf = RandomForestClassifier()

In [20]:
lr.fit(xtrain,ytrain)

/opt/conda/envs/Python-3.10/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [21]:
dt.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [22]:
rf.fit(xtrain,ytrain)

/tmp/wsuser/ipykernel_168/2224009558.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(xtrain,ytrain)


RandomForestClassifier()

In [23]:
ypred_lr = lr.predict(xtest)
ypred_dt = dt.predict(xtest)
ypred_rf = rf.predict(xtest)

In [24]:
ypred_lr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
ypred_dt

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [26]:
ypred_rf

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
confusion_matrix(ytest,ypred_lr)

array([[52,  0],
       [28,  0]])

In [29]:
confusion_matrix(ytest,ypred_dt)

array([[44,  8],
       [ 1, 27]])

In [30]:
confusion_matrix(ytest,ypred_rf)

array([[47,  5],
       [ 1, 27]])

In [31]:
# Save the model

import pickle

In [32]:
pickle.dump(rf,open('classification_rf.pkl','wb'))

In [33]:
!pip install -U ibm-watson-machine-learning

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 24.9 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: ibm-watson-machine-learning
    Found existing installation: ibm-watson-machine-learning 1.0.326
    Uninstalling ibm-watson-machine-learning-1.0.326:
      Successfully uninstalled ibm-watson-machine-learning-1.0.326


In [34]:
from ibm_watson_machine_learning import APIClient
import json
import numpy as np

In [39]:
# Authenticate and set space creating dictionary
wml_credentials = {
    "apikey":"8KfVKH2y4qd8QqJ2o_t5S49iSuCCDsz4IBcLSpJPkMfQ",
    "url":"https://us-south.ml.cloud.ibm.com"
}

In [40]:
wml_client =  APIClient(wml_credentials)

In [42]:
wml_client.spaces.list()    # checking 

Note: 'limit' is not provided. Only first 50 records will be displayed if the number of records exceed 50
------------------------------------  -------------  ------------------------
ID                                    NAME           CREATED
dbd1cea2-5352-46b6-bd19-5bd62b4a0e0b  IBM_HC_deploy  2023-11-15T03:37:31.450Z
------------------------------------  -------------  ------------------------


ID           NAME  \
0  dbd1cea2-5352-46b6-bd19-5bd62b4a0e0b  IBM_HC_deploy   

                    CREATED  
0  2023-11-15T03:37:31.450Z

In [43]:
SPACE_ID="dbd1cea2-5352-46b6-bd19-5bd62b4a0e0b"  #STORING TO OTHER VARIABLE ACTIVATING

In [44]:
wml_client.set.default_space(SPACE_ID)

'SUCCESS'

In [45]:
MODEL_NAME = 'demoModel'
DEPLOYMENT_NAME = 'demoMOdelDep'
BEST_MODEL = rf

In [48]:
#set python version
software_spec_uid = wml_client.software_specifications.get_id_by_name('runtime-22.2-py3.10')

In [50]:
#set model meta
model_props = {
    wml_client.repository.ModelMetaNames.NAME: MODEL_NAME,
    wml_client.repository.ModelMetaNames.TYPE: 'scikit-learn_1.1',
    wml_client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid
}

In [51]:
# save model
model_details = wml_client.repository.store_model(
    model =BEST_MODEL,
    meta_props = model_props,
    training_data = xtrain,
    training_target = ytrain
)

In [52]:
model_details

{'entity': {'hybrid_pipeline_software_specs': [],
  'label_column': 'Purchased',
  'schemas': {'input': [{'fields': [{'name': 'Gender', 'type': 'int64'},
      {'name': 'Age', 'type': 'int64'},
      {'name': 'EstimatedSalary', 'type': 'int64'}],
     'id': '1',
     'type': 'struct'}],
   'output': []},
  'software_spec': {'id': 'b56101f1-309d-549b-a849-eaa63f77b2fb',
   'name': 'runtime-22.2-py3.10'},
  'training_data_references': [{'id': '1',
    'location': {},
    'schema': {'fields': [{'name': 'Gender', 'type': 'int64'},
      {'name': 'Age', 'type': 'int64'},
      {'name': 'EstimatedSalary', 'type': 'int64'}],
     'id': '1',
     'type': 'DataFrame'},
    'type': 'container'}],
  'type': 'scikit-learn_1.1'},
 'metadata': {'created_at': '2023-11-15T04:03:43.478Z',
  'id': '969a03d9-ba00-4d53-b86c-e5a5cfff317d',
  'modified_at': '2023-11-15T04:03:50.534Z',
  'name': 'demoModel',
  'owner': 'IBMid-664003XR27',
  'resource_key': '74d74eee-d5b0-425a-88fc-dd9e25fbe454',
  'space_id'

In [53]:
model_uid = wml_client.repository.get_model_id(model_details)
model_uid

'969a03d9-ba00-4d53-b86c-e5a5cfff317d'

In [55]:
#set meta
deployment_props = {
    wml_client.deployments.ConfigurationMetaNames.NAME:DEPLOYMENT_NAME,
    wml_client.deployments.ConfigurationMetaNames.ONLINE: {}
}

In [ ]:
# Deploy

    deployment1 = wml_client.deployments.create(
        artifact_uid = model_uid,
        meta_props =
    )
