class 3

In [ ]:
!pip install pandas

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 50_Startups.csv to 50_Startups.csv


In [ ]:
dataset = pd.read_csv('50_Startups.csv')

In [ ]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [ ]:
!pip install scikit-learn

# LabelEncoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['State'] = le.fit_transform(dataset['State'])   # for converting in label

In [ ]:
dataset.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

OneHotEncoding feature less

In [ ]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4:5].values

In [ ]:
x.dtype

dtype('float64')

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(x[:,3:4]).toarray()
x =np.delete(x,3,axis=1)
x =np.concatenate((z,x),axis=1)

In [ ]:
x

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

train test & split

In [ ]:
from sklearn.model_selection import train_test_split   # preprocessing  split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)  #random_state is for soft linking

#hyper parameter change

In [ ]:
x_train.shape

(40, 6)

In [ ]:
y_train.shape

(40, 1)

In [ ]:
x_test

array([[0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 6.6051520e+04,
        1.8264556e+05, 1.1814820e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0067196e+05,
        9.1790610e+04, 2.4974455e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.0191308e+05,
        1.1059411e+05, 2.2916095e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 2.7892920e+04,
        8.4710770e+04, 1.6447071e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 7.2107600e+04,
        1.2786455e+05, 3.5318381e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 2.0229590e+04,
        6.5947930e+04, 1.8526510e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 6.1136380e+04,
        1.5270192e+05, 8.8218230e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 7.3994560e+04,
        1.2278275e+05, 3.0331926e+05],
       [0.0000000e+00, 1.0000000e+00,

Model Building

In [ ]:
!pip install keras

In [ ]:
!pip install tensorflow

class 2

other class

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Employee_Salary_Dataset.csv to Employee_Salary_Dataset.csv


In [ ]:
df= pd.read_csv('Employee_Salary_Dataset.csv')

In [ ]:
df

ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

In [ ]:
df.shape

(35, 5)

In [ ]:
df.head()

ID  Experience_Years  Age  Gender  Salary
0   1                 5   28  Female  250000
1   2                 1   21    Male   50000
2   3                 3   23  Female  170000
3   4                 2   22    Male   25000
4   5                 1   17    Male   10000

In [ ]:
df.head(10)

ID  Experience_Years  Age  Gender   Salary
0   1                 5   28  Female   250000
1   2                 1   21    Male    50000
2   3                 3   23  Female   170000
3   4                 2   22    Male    25000
4   5                 1   17    Male    10000
5   6                25   62    Male  5001000
6   7                19   54  Female   800000
7   8                 2   21  Female     9000
8   9                10   36  Female    61500
9  10                15   54  Female   650000

In [ ]:
df.tail()

ID  Experience_Years  Age  Gender   Salary
30  31                10   34    Male    80000
31  32                15   54    Male   900000
32  33                20   55  Female  1540000
33  34                19   53  Female  9300000
34  35                16   49    Male  7600000

In [ ]:
df.describe()

ID  Experience_Years        Age        Salary
count  35.000000          35.00000  35.000000  3.500000e+01
mean   18.000000           9.20000  35.485714  2.059147e+06
std    10.246951           7.55295  14.643552  3.170124e+06
min     1.000000           1.00000  17.000000  3.000000e+03
25%     9.500000           2.50000  22.500000  2.250000e+04
50%    18.000000           6.00000  29.000000  2.500000e+05
75%    26.500000          15.00000  53.500000  3.270000e+06
max    35.000000          27.00000  62.000000  1.000000e+07

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                35 non-null     int64 
 1   Experience_Years  35 non-null     int64 
 2   Age               35 non-null     int64 
 3   Gender            35 non-null     object
 4   Salary            35 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 1.5+ KB


finding null value

In [ ]:
df.isnull().sum()

ID                  0
Experience_Years    0
Age                 0
Gender              0
Salary              0
dtype: int64

Handle the null values

In [ ]:
df.Age=df.Age.fillna(df.Age.median)
df.Salary = df.Salary.fillna(df.Salary.mean)

In [ ]:
df

ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

remove all row of this null value

In [ ]:
df.dropna()

ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

Loc and iLoc use to access the dataf

*dataframe* is 2d row and coloum and series is 1d

In [ ]:
df

ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

loc is use for label indexing

In [ ]:
df.loc[1:5]

ID  Experience_Years  Age  Gender   Salary
1   2                 1   21    Male    50000
2   3                 3   23  Female   170000
3   4                 2   22    Male    25000
4   5                 1   17    Male    10000
5   6                25   62    Male  5001000

In [ ]:
df.loc[34:35]

ID  Experience_Years  Age Gender   Salary
34  35                16   49   Male  7600000

In [ ]:
df.loc[df.Age>40]

ID  Experience_Years  Age  Gender    Salary
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
9   10                15   54  Female    650000
17  18                15   54  Female   7900000
20  21                15   54    Male   6570000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

In [ ]:
df.loc[df['Age']>50]

ID  Experience_Years  Age  Gender    Salary
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
9   10                15   54  Female    650000
17  18                15   54  Female   7900000
20  21                15   54    Male   6570000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000

iloc is use for integer indxing

iloc

In [ ]:
df.iloc[:,:]   # start:end

ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

In [ ]:
df.iloc[:,0:2]

ID  Experience_Years
0    1                 5
1    2                 1
2    3                 3
3    4                 2
4    5                 1
5    6                25
6    7                19
7    8                 2
8    9                10
9   10                15
10  11                 4
11  12                 6
12  13                14
13  14                11
14  15                 2
15  16                 4
16  17                10
17  18                15
18  19                 2
19  20                10
20  21                15
21  22                 4
22  23                 5
23  24                 1
24  25                 4
25  26                 3
26  27                 1
27  28                27
28  29                19
29  30                 2
30  31                10
31  32                15
32  33                20
33  34                19
34  35                16

In [ ]:
df.iloc[0:5,:3]

ID  Experience_Years  Age
0   1                 5   28
1   2                 1   21
2   3                 3   23
3   4                 2   22
4   5                 1   17

In [ ]:
df.iloc[0:5,3]

0    Female
1      Male
2    Female
3      Male
4      Male
Name: Gender, dtype: object

In [ ]:
df.iloc[[7,9],0:2]

ID  Experience_Years
7   8                 2
9  10                15

In [ ]:
df.iloc[:,[0,2]]

ID  Age
0    1   28
1    2   21
2    3   23
3    4   22
4    5   17
5    6   62
6    7   54
7    8   21
8    9   36
9   10   54
10  11   26
11  12   29
12  13   39
13  14   40
14  15   23
15  16   27
16  17   34
17  18   54
18  19   21
19  20   36
20  21   54
21  22   26
22  23   29
23  24   21
24  25   23
25  26   22
26  27   18
27  28   62
28  29   54
29  30   21
30  31   34
31  32   54
32  33   55
33  34   53
34  35   49

In [ ]:
x=df.iloc[:,-1]

In [ ]:
x

0       250000
1        50000
2       170000
3        25000
4        10000
5      5001000
6       800000
7         9000
8        61500
9       650000
10      250000
11     1400000
12     6000050
13      220100
14        7500
15       87000
16      930000
17     7900000
18       15000
19      330000
20     6570000
21       25000
22     6845000
23        6000
24        8900
25       20000
26        3000
27    10000000
28     5000000
29        6100
30       80000
31      900000
32     1540000
33     9300000
34     7600000
Name: Salary, dtype: int64

In [ ]:
x=df.iloc[:,-1:]

In [ ]:
x

Salary
0     250000
1      50000
2     170000
3      25000
4      10000
5    5001000
6     800000
7       9000
8      61500
9     650000
10    250000
11   1400000
12   6000050
13    220100
14      7500
15     87000
16    930000
17   7900000
18     15000
19    330000
20   6570000
21     25000
22   6845000
23      6000
24      8900
25     20000
26      3000
27  10000000
28   5000000
29      6100
30     80000
31    900000
32   1540000
33   9300000
34   7600000

In [ ]:
type(x)

pandas.core.frame.DataFrame

In [ ]:
df.iloc[:,range(0,3)]

ID  Experience_Years  Age
0    1                 5   28
1    2                 1   21
2    3                 3   23
3    4                 2   22
4    5                 1   17
5    6                25   62
6    7                19   54
7    8                 2   21
8    9                10   36
9   10                15   54
10  11                 4   26
11  12                 6   29
12  13                14   39
13  14                11   40
14  15                 2   23
15  16                 4   27
16  17                10   34
17  18                15   54
18  19                 2   21
19  20                10   36
20  21                15   54
21  22                 4   26
22  23                 5   29
23  24                 1   21
24  25                 4   23
25  26                 3   22
26  27                 1   18
27  28                27   62
28  29                19   54
29  30                 2   21
30  31                10   34
31  32                15   54
32  33                20   55
33  34                19   53
34  35                16   49

How to find diffrent categories with count

In [ ]:
df.columns

Index(['ID', 'Experience_Years', 'Age', 'Gender', 'Salary'], dtype='object')

In [ ]:
df['Gender'].value_counts()

Female    18
Male      17
Name: Gender, dtype: int64

class 4

importing libraries

In [ ]:
!pip install keras

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow.keras   # tensorflow and keras use together
from tensorflow.keras.models import Sequential  # sequencial first hiden layer second and soon
from tensorflow.keras.layers import Dense  # all the node connected in dense

initialize the model

In [ ]:
model = Sequential()   # anhy name S cap for sequence all hiden layer come

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 50_Startups.csv to 50_Startups (1).csv


In [ ]:
dataset = pd.read_csv('50_Startups.csv')  # it 50 startup

In [ ]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

for label

In [ ]:
!pip install scikit-learn

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['State'] = le.fit_transform(dataset['State'])   # for converting in label

In [ ]:
dataset.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

for onehot

In [ ]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4:5].values

In [ ]:
x.dtype

dtype('float64')

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(x[:,3:4]).toarray()
x =np.delete(x,3,axis=1)
x =np.concatenate((z,x),axis=1)

In [ ]:
x   # converting in to array

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

Train, Test & Split

In [ ]:
from sklearn.model_selection import train_test_split   # preprocessing  split
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size = 0.2, random_state=0)  #random_state is for soft linking

#hyper parameter change

In [ ]:
x_train.shape

(40, 6)

In [ ]:
y_train.shape

(40, 1)

In [ ]:
x_test

array([[0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 6.6051520e+04,
        1.8264556e+05, 1.1814820e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0067196e+05,
        9.1790610e+04, 2.4974455e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.0191308e+05,
        1.1059411e+05, 2.2916095e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 2.7892920e+04,
        8.4710770e+04, 1.6447071e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 7.2107600e+04,
        1.2786455e+05, 3.5318381e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 2.0229590e+04,
        6.5947930e+04, 1.8526510e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 6.1136380e+04,
        1.5270192e+05, 8.8218230e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 7.3994560e+04,
        1.2278275e+05, 3.0331926e+05],
       [0.0000000e+00, 1.0000000e+00,

In [ ]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

Model Building

IMporot libraries

add layers

In [ ]:
model.add(Dense(units=4,activation='relu'))   # model is name is artif node connect to dense unit is variable relu is use to activation fun  input layer

In [ ]:
model.add(Dense(units=12,activation='relu'))   # 1st hidden layer

In [ ]:
model.add(Dense(units=8,activation='relu'))      # 2nd hidden layer

In [ ]:
model.add(Dense(units=9,activation='relu'))     # 3rd hidden layer

output Layer

In [ ]:
model.add(Dense(units=1))

Compile The Model

In [ ]:
model.compile(optimizer = 'adam' , loss = 'mse', metrics = ['mse'])   # adam is optimizer mean square error adam is same like gradient codt funtion is loss
#mse mean square error

Fit The model

In [ ]:
model.fit(x_train, y_train, batch_size = 15, epochs = 100)   # epochs  one pass to whole dataset

Epoch 1/100
3/3 [==============================] - 1s 9ms/step - loss: 5313887232.0000 - mse: 5313887232.0000
Epoch 2/100
3/3 [==============================] - 0s 6ms/step - loss: 4628380160.0000 - mse: 4628380160.0000
Epoch 3/100
3/3 [==============================] - 0s 8ms/step - loss: 3938817280.0000 - mse: 3938817280.0000
Epoch 4/100
3/3 [==============================] - 0s 7ms/step - loss: 3388215296.0000 - mse: 3388215296.0000
Epoch 5/100
3/3 [==============================] - 0s 9ms/step - loss: 2778520064.0000 - mse: 2778520064.0000
Epoch 6/100
3/3 [==============================] - 0s 7ms/step - loss: 2368745984.0000 - mse: 2368745984.0000
Epoch 7/100
3/3 [==============================] - 0s 7ms/step - loss: 1901108224.0000 - mse: 1901108224.0000
Epoch 8/100
3/3 [==============================] - 0s 7ms/step - loss: 1559583360.0000 - mse: 1559583360.0000
Epoch 9/100
3/3 [==============================] - 0s 8ms/step - loss: 1273502464.0000 - mse: 1273502464.0000
Epoch 10/1

In [ ]:
model.fit(x_train,y_train, batch_size=15,epochs=800)   # at last give 500 epochs or 550

Epoch 1/800
3/3 [==============================] - 0s 6ms/step - loss: 125497648.0000 - mse: 125497648.0000
Epoch 2/800
3/3 [==============================] - 0s 5ms/step - loss: 126007312.0000 - mse: 126007312.0000
Epoch 3/800
3/3 [==============================] - 0s 6ms/step - loss: 126462592.0000 - mse: 126462592.0000
Epoch 4/800
3/3 [==============================] - 0s 7ms/step - loss: 125723800.0000 - mse: 125723800.0000
Epoch 5/800
3/3 [==============================] - 0s 7ms/step - loss: 125170984.0000 - mse: 125170984.0000
Epoch 6/800
3/3 [==============================] - 0s 9ms/step - loss: 126527040.0000 - mse: 126527040.0000
Epoch 7/800
3/3 [==============================] - 0s 7ms/step - loss: 125634920.0000 - mse: 125634920.0000
Epoch 8/800
3/3 [==============================] - 0s 8ms/step - loss: 126651096.0000 - mse: 126651096.0000
Epoch 9/800
3/3 [==============================] - 0s 6ms/step - loss: 127414120.0000 - mse: 127414120.0000
Epoch 10/800
3/3 [==========

search good value of mse

Test the model

In [ ]:
 y_pred=model.predict(x_test)  # test our model on testing data


1/1 [==============================] - 0s 26ms/step


In [ ]:
 y_pred   # predicted value


array([[120933.11 ],
       [115994.97 ],
       [116738.51 ],
       [ 57508.87 ],
       [168177.95 ],
       [135935.81 ],
       [ 58207.008],
       [104892.586],
       [124711.23 ],
       [152312.73 ]], dtype=float32)

In [ ]:
  y_test   # original value

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

Calculate R2_score or cofficient of determination

In [ ]:
from sklearn.metrics import r2_score # show diff in original and predic value
accuracy = r2_score(y_test,y_pred)


In [ ]:
accuracy   #100 means model overfiting  go 88

0.6208619772074305

class 5

image Augmentation

use gpu,tpu

if you dataset has 5000 image so use tpu

image is in grid

In [ ]:
!pip install tensorflow
   ###  set gpu and tpu  graphic processing unit  tensorflow processing unit
# tpu depelop by google it u use machine learnig model make it faster
#tpu specialy for deep learnig and machinel learrning task

In [ ]:
!pip install keras


In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator   #data augmentation and producing diff image


In [ ]:
train_datagen=ImageDataGenetator(rescale=1/255,zoom_range=0.2,horizontal_flip=True,verical_flip=False)  # initilisign image data genratior for image producing 4 copy with diffrent angle
#  rescale for normilizing image in range 0-255 this i give rang in 0-1


In [ ]:
test_datagen=ImageDataGentator(rescale=1/255)    #


In [ ]:
x_train=train_datagen.flow_from_directory()